DELIMITER \\
CREATE PROCEDURE ListAllSubscribers()
BEGIN 
	DECLARE CUR_NAME VARCHAR(100);
    DECLARE DONE INT DEFAULT FALSE;
    DECLARE NAMECURSOR CURSOR FOR 
		SELECT SubscriberName from Subscribers;
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET DONE= TRUE;
    OPEN NAMECURSOR;
    read_loop: LOOP
		FETCH NAMECURSOR INTO CUR_NAME;
        IF DONE THEN 
			LEAVE read_loop;
		END IF;
        SELECT CUR_NAME AS Subscriber_Name;
	END LOOP;
    CLOSE NAMECURSOR;
END\\
DELIMITER ;

-- call ListAllSubscribers();